### ISSUE TITLE
PUT api/User only accepts Uppercase variables

### ISSUE THREAD

**Issue by MauriceNino** [gamerpals/Backend#12]
# Expected Behavior
JSON default is lowercase variables, so the backend should be able to handle that.

# Current Behavior
When calling with "profileDescription":
```
System.FormatException: Element 'profileDescription' does not match any field or property of class GamerPalsBackend.DataObjects.Models.User.
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
   at MongoDB.Bson.Serialization.IBsonSerializerExtensions.Deserialize[TValue](IBsonSerializer`1 serializer, BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonSerializer.Deserialize[TNominalType](BsonDocument document, Action`1 configurator)
```

When calling with "ProfileDescription":
200 OK

# Possible Solution
Force uppercase on first char programmatically.
OR
Transform JSON correctly (preferred)

# Detailed Description
/

**Comment by MauriceNino** [comment]
Please also check other PUT methods, as they might face the same issue.
